### ISSUE TITLE
Custom .tf files handling

### ISSUE THREAD

**Issue by jlausuch** [jlausuch/qatrfm-lib#6]
Currently, if there is a .tf file in the same directory where the python file is located, it will take it as the .tf to be used for Terraform instead of the default one located in qatrfm/config/ directory.

Improvements (up to discussion)

1) Check if there are more than one .tf files and display a warning if so.
2) New CLI parameter to specify a custom .tf to use

**Comment by jlausuch** [comment]
Fixed in PR: https://github.com/jlausuch/qatrfm-lib/pull/11

**Comment by jlausuch** [comment]
@cfconrad could you add any comments about the solution?

**Comment by cfconrad** [comment]
The test is specified with parameter `-t`.

**Discover Testcases:**
The parameter can  be a file or directory. If it is a file, the file is parsed for classes extending `TrfmTestCase`. Each found class will be treated as testcase and executed.
If it is  a directory, it search recursive for `*.py` files and parse them accordingly.
The name of the testcase, is the name of the Class.

**Obtain `*.tf` file:**
For each found testcase we use the same `*.tf` file discovery. First we look for a `*.tf` file in the same folder as the `*.py` file is. If this file doesn't exists, the default file from `qatrfm/config/` is used.

I currently do not see the benefit of point `2.`, overwrite the TF file with something custom.

Open issue: https://github.com/jlausuch/qatrfm-lib/issues/17
